image: pythondiscord/bot-ci:latest

stages:
  - test
  - build

test:
  tags:
  - docker

  stage: test

  script:
    - pipenv install --dev --deploy
    - pipenv run lint

build:
  tags:
  - docker

  services:
    - docker:dind

  stage: build
  script:
    - sh scripts/deploy.sh
