bot:
    help_prefix: 'bot.'
    token: !REQUIRED_ENV 'BOT_TOKEN'

    cooldowns:
        # Per channel, per tag.
        tags: 60

    emojis:
        green_chevron: '<:greenchevron:418104310329769993>'
        red_chevron: '<:redchevron:418112778184818698>'
        white_chevron: '<:whitechevron:418110396973711363>'
        lemoneye2: '<:lemoneye2:435193765582340098>'


guild:
    id: 267624335836053506

    channels:
        announcements: 354619224620138496
        bot: 267659945086812160
        checkpoint_test: 422077681434099723
        devlog: 409308876241108992
        devtest: 414574275865870337
        help0: 303906576991780866
        help1: 303906556754395136
        help2: 303906514266226689
        help3: 439702951246692352
        help4: 451312046647148554
        helpers: 385474242440986624
        modlog: 282638479504965634
        message_change_logs: 467752170159079424
        python: 267624335836053506
        verification: 352442727016693763
        off_topic_0: 291284109232308226
        off_topic_1: 463035241142026251
        off_topic_2: 463035268514185226

    roles:
        admin: 267628507062992896
        announcements: 463658397560995840
        champion: 430492892331769857
        contributor: 295488872404484098
        devops: 409416496733880320
        jammer: 423054537079783434
        moderator: 267629731250176001
        owner: 267627879762755584
        verified: 352427296948486144
        helpers: 267630620367257601


keys:
    deploy_bot: !ENV 'DEPLOY_BOT_KEY'
    deploy_site: !ENV 'DEPLOY_SITE'
    omdb: !ENV 'OMDB_API_KEY'
    site_api: !ENV 'BOT_API_KEY'
    youtube: !ENV 'YOUTUBE_API_KEY'


clickup:
    key: !ENV 'CLICKUP_KEY'
    space: 757069
    team: 754996


rabbitmq:
    host: "pdrmq"
    password: !ENV "RABBITMQ_DEFAULT_PASS"
    port: 5672
    username: !ENV "RABBITMQ_DEFAULT_USER"


urls:
    bot_avatar: 'https://raw.githubusercontent.com/discord-python/branding/master/logos/logo_circle/logo_circle.png'
    deploy: !ENV 'DEPLOY_URL'
    gitlab_bot_repo: 'https://gitlab.com/discord-python/projects/bot'
    omdb: 'http://omdbapi.com'
    site: 'pythondiscord.com'
    site_bigbrother_api: 'https://api.pythondiscord.com/bot/bigbrother'
    site_docs_api: 'https://api.pythondiscord.com/bot/docs'
    site_facts_api: 'https://api.pythondiscord.com/bot/snake_facts'
    site_hiphopify_api: 'https://api.pythondiscord.com/bot/hiphopify'
    site_idioms_api: 'https://api.pythondiscord.com/bot/snake_idioms'
    site_names_api: 'https://api.pythondiscord.com/bot/snake_names'
    site_off_topic_names_api: 'https://api.pythondiscord.com/bot/off-topic-names'
    site_quiz_api: 'https://api.pythondiscord.com/bot/snake_quiz'
    site_settings_api: 'https://api.pythondiscord.com/bot/settings'
    site_special_api: 'https://api.pythondiscord.com/bot/special_snakes'
    site_tags_api: 'https://api.pythondiscord.com/bot/tags'
    site_user_api: 'https://api.pythondiscord.com/bot/users'
    site_user_complete_api: 'https://api.pythondiscord.com/bot/users/complete'
    status: !ENV 'STATUS_URL'
    paste_service: 'https://paste.pydis.com/{key}'
